server:
  port: 8080 # El Frontend siempre apuntara aqui

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        # Ruta para el servicio de Luis
        - id: ruta-catalogo
          uri: lb://servicio-catalogo
          predicates:
            - Path=/api/v1/catalogo/**
            
        # Ruta para nuestro Orquestador
        - id: ruta-orquestador-pos
          uri: lb://servicio-ventapos
          predicates:
            - Path=/api/v1/ventas-pos/**
            
        # Ruta para nuestro Inventario
        - id: ruta-inventario
          uri: lb://servicio-inventario
          predicates:
            - Path=/api/v1/inventario/**
            
        # Ruta para el Orquestador Web
        - id: ruta-orquestador-web
          uri: lb://servicio-ventaweb
          predicates:
            - Path=/api/v1/ventas-web/**

        # Ruta para Transporte (Guias PDF)
        - id: ruta-transporte
          uri: lb://servicio-transporte
          predicates:
            - Path=/api/v1/transporte/**
            
        # Ruta para Clientes
        - id: ruta-clientes
          uri: lb://servicio-clientes
          predicates:
            - Path=/api/v1/clientes/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
